# Generated by Django 5.2.1 on 2025-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_unique_recipe_per_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.SlugField(blank=True, editable=False, max_length=15, unique=True, verbose_name='Short link code'),
        ),
    ]
